### ISSUE TITLE
Change variable in file form.html

### ISSUE THREAD

**Issue by emicba126** [codenerix/django-codenerix#14]
Hola.
Les comento que he encontrado un error en las variables en el template form.html.
Ubicacion: django-codenerix/codenerix/templates/codenerix/form.html

Lineas:
**493:** {% if group.html_helper_**pre** %}
**495:** {{group.html_helper_**pre**|safe}}

Se debe corregir el "pre" por "post":
**493:** {% if group.html_helper_**post** %}
**495:** {{group.html_helper_**post**|safe}}

No se si esto debo publicarlo de esta forma o si es lo correcto.
En lo que pueda deseo contribuir con el proyecto ya que actualmente lo estoy utilizando.
Saludos.

**Comment by juanmitaboada** [comment]
Hola, acabo de aplicar tu cambio a la rama de desarrollo y dado que estos días atrás hemos introducido ciertas mejoras también he publicado un paquete nuevo en pypy y he hecho un merge con master. ¡¡¡Gracias!!!

**Comment by juanmitaboada** [comment]
Para contribuir en el proyecto, ojea esto:
http://panamahitek.com/como-contribuir-en-proyectos-con-git-y-github/
https://www.youtube.com/watch?v=32yOvBHjf8c
