### ISSUE TITLE
Error al Exportar a .xlsx con valores decimales

### ISSUE THREAD

**Issue by emicba126** [codenerix/django-codenerix#42]
Al querer exportar a .xlsx un listado con valores tipo Decimal o Float, se genera el siguiente error:
**"Parser must be a string or character stream, not float"**

Parece ser que no acepta exportar valores decimales; como si previamente habria que convertirlos a str().

**Comment by juanmitaboada** [comment]
La exportación .XLSX ha quedado resuelta en la versión 4.0.2 de CODENERIX (que además actualiza el sistema de a Django 4.x)
