### ISSUE TITLE
ImportError: cannot import name 'save_virtual_workbook' from 'openpyxl.writer.excel' (Django/erp/erp_virtual_environment/lib/python3.10/site-packages/openpyxl/writer/excel.py)

### ISSUE THREAD

**Issue by RomjanHossain** [codenerix/django-codenerix#46]

**Comment by juanmitaboada** [comment]
Thank you for your report, it seems to be a **deprecated** import. We will publish a new version correcting this bug in the next few days.

**Comment by Soleronline** [comment]
There is a new Codenerix version 4.0.23. You can install it with 'pip' from pypi
